import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr=np.linspace(1,10,num=4)
print(arr)
arr=np.arange(1,10,2)
print(arr)
arr=np.zeros(10)
print(arr)
arr=np.ones(5)
print(arr)

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1+arr2)
print(np.sum(arr1))
print(np.sum(arr1 ,axis=0))
print(np.sum(arr1 ,axis=1))

print(np.prod(arr2))
print(np.prod(arr2 ,axis=0))
print(np.prod(arr2 ,axis=1))

arr3=np.array([1,2,3,4,5,6])
arr=arr3.reshape(3,2)
print(arr)
print(arr.T)

print(arr1[0:2,:])
print(arr1[:,2])
joined = np.vstack((arr1, arr2))
print(joined)
print(arr2.reshape(6))
print(arr2.flatten())
print(np.split(arr1,2))